apiVersion: apps/v1
kind: Deployment
metadata:
  name: donate-books-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donate-books-app
  template:
    metadata:
      labels:
        app: donate-books-app
    spec:
      containers:
      - name: donate-books-app
        image: bhavanagm15/donatebooks-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017/donatebooks"
        - name: SESSION_SECRET
          value: "bookSwapSecretKey"
        - name: JWT_SECRET
          value: "jwtsecret123"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: donate-books-service
spec:
  selector:
    app: donate-books-app
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
