version: "3.9"
services:
  app:
    build: .
    container_name: donate-books-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/donatebooks
      - SESSION_SECRET=supersecret
      - JWT_SECRET=jwtsecret123
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: donate-books-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
